### ISSUE TITLE
Illegal Instruction error Intel i7-3540M CPU @ 3.00GHz

### ISSUE THREAD

**Issue by 6latt** [abacaj/replit-3B-inference#9]
Messed with thread parameter to see if reducing number of threads would help. No dice

**Comment by 6latt** [comment]
![image](https://github.com/abacaj/replit-3B-inference/assets/103127735/f6a32f6e-8004-4025-8ef1-d34f896dec55)


Found this in ctransformers documentation:
If you are getting `illegal instruction` error, try using `lib='avx'` or `lib='basic'`:

going to try

**Comment by 6latt** [comment]
this fixed my issue, however, now it's not recognizing replit as a model type

`Model type 'replit' is not supported.
Traceback (most recent call last):
  File "/root/replit-3B-inference/inference.py", line 47, in <module>
    llm = AutoModelForCausalLM.from_pretrained(
  File "/root/replit-3B-inference/env/lib/python3.10/site-packages/ctransformers/hub.py", line 157, in from_pretrained
    return LLM(
  File "/root/replit-3B-inference/env/lib/python3.10/site-packages/ctransformers/llm.py", line 214, in __init__
    raise RuntimeError(
RuntimeError: Failed to create LLM 'replit' from '/root/replit-3B-inference/models/replit-v2-codeinstruct-3b.q4_1.bin'.`

**Comment by 6latt** [comment]
`if __name__ == "__main__":
    config = AutoConfig.from_pretrained(
        os.path.abspath("models"),
        context_length=2048,
    )
    llm = AutoModelForCausalLM.from_pretrained(
        os.path.abspath("models/replit-v2-codeinstruct-3b.q4_1.bin"),
        model_type='replit',
        lib='avx',
        config=config,
    )`
    
    is the problematic block, just for future reference
